sudo: false
language: python
python:
- '2.7'
- '3.6'
services:
- memcached
before_script:
- pip install -e .
- pip install pycodestyle
- pip install coverage
- pip install python-coveralls
- cp travis-ci/manage.py manage.py
script:
- pycodestyle rc_django/ --exclude=migrations
- python -m compileall rc_django/
- COVERAGE_FILE=.coverage coverage run --source=rc_django/ --omit=rc_django/migrations/* manage.py test rc_django
- cp travis-ci/settings_without_installed_app.py travis-ci/settings.py
- COVERAGE_FILE=.coverage_app_label coverage run --source=rc_django/ --omit=rc_django/migrations/* manage.py test rc_django.tests.test_models
- coverage combine
after_success:
- coveralls
before_deploy:
- find rc_django/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > rc_django/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: deUQ6IkYWfo7nNcT0r7eGE+g6NM0b7B3AmWhzf1VkufRXsVZOkr5jljX5BpoJ3+UgOhWSW99OgF51xSRSs5WYYrm3PG9m7hRAFvM3gBSQhJKqWvfyX3I9nFVIKYJ3lRH5dVDY5S3VRFkk5OjLNyrTJJjMEew+b0Hdp1m0aqFdJUHwsIaupRtrmjdDK+mMpPv4g6zT8I7dzYt3g4xg7iMy2B2F7to7HRYqS1/KEJVEv8P/fH2xFFE8sCGJMpiJnvE5L0ES5T1SBUtIjoMoB+g18P+VEO0BumHzw49TKhQJFZM0jKfaCqqPBFD6QmC6Pxc6iDdUqrHsG2cLe8ZIytjN4/taL22CfLEMm25QW2wT7Lvkbpn4kcq39db7CslOMwvO9p/5Dk4oxCK22iPnQdHU8rGK0Cj86rg/9zdtHLDlts4QbQ3CEusTFHZVXpdelmYCBr491Gh9N003R3JZRMqm5ABkd6ENyZUxLXe1cKKpiLF2bYMoQv2zpekooZqMQtcrJ3Muv+NjmP7xGOyCkkjxr4iCZVHuScl8K6gu+0S2HA0cI0+59279BxoJVhiv8ejcEiKTI4c5Gp5Qz+MlpIgi7ACsHRdq6SO0lX/CXv99sLi+4lTC8zcG28ghMjPDckbUSuJL9VGxQ5S8SLR6CwHFiAkzDt0nKKkfPUG0FGYwY8=
  on:
    tags: true
    python: '3.6'
