# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheentry',
            name='url',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
    ]
