# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import datetime


def add_url_keys(apps, schema_editor):
    CacheEntry = apps.get_model('rc_django', 'CacheEntry')
    for entry in CacheEntry.objects.all():
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rc_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheentry',
            name='url_key',
            field=models.SlugField(default=datetime.datetime.now, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cacheentry',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='cacheentry',
            unique_together=set([('service', 'url_key')]),
        ),
        migrations.RunPython(add_url_keys),
    ]
