# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 16:03
from __future__ import unicode_literals

from django.db import migrations


def add_url_keys(apps, schema_editor):
    CacheEntry = apps.get_model('rc_django', 'CacheEntry')
    for entry in CacheEntry.objects.all():
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rc_django', '0002_auto_20170504_1601'),
    ]

    operations = [
        migrations.RunPython(add_url_keys),
    ]
